# Turns spec/wire.json into C macros for test_spec.c.
"/* Generated from spec/wire.json by tests/wire.jq. */",
"#define SPEC_RING_MAGIC UINT64_C(\(.ring.magic))",
"#define SPEC_RING_VERSION \(.ring.version)u",
"#define SPEC_HEADER_SIZE \(.ring.header_size)u",
"#define SPEC_CACHE_LINE \(.ring.cache_line)u",
"#define SPEC_MIN_CAPACITY \(.ring.min_capacity)u",
"#define SPEC_RECORD_HEADER_SIZE \(.ring.record_header_size)u",
"#define SPEC_RECORD_ALIGNMENT \(.ring.record_alignment)u",
"#define SPEC_TYPE_PADDING UINT32_C(\(.ring.type_padding))",
"#define SPEC_CONTROL_SIZE \(.ring.control_size)u",
"#define SPEC_FIELD_COUNT \(.ring.fields | length)",
"#define SPEC_FIELDS \\",
(.ring.fields[] | "\t{\"\(.name)\", \(.offset), \(.size)}, \\"),
"",
"#define SPEC_SLOTS_OFFSET \(.ring.claim_slots.offset)u",
"#define SPEC_SLOTS_COUNT \(.ring.claim_slots.count)u",
"#define SPEC_SLOT_SIZE \(.ring.claim_slots.slot_size)u",
"#define SPEC_NO_INTENT UINT64_C(\(.ring.claim_slots.no_intent))",
"#define SPEC_SLOT_FIELD_COUNT \(.ring.claim_slots.fields | length)",
"#define SPEC_SLOT_FIELDS \\",
(.ring.claim_slots.fields[] | "\t{\"\(.name)\", \(.offset), \(.size)}, \\"),
"",
"#define SPEC_PROC_NONE UINT64_C(\(.proc_id.none))",
"#define SPEC_PROC_PENDING UINT64_C(\(.proc_id.pending))",
"#define SPEC_PROC_WATCHABLE_BIT \(.proc_id.watchable_bit)",
"#define SPEC_PROC_ALWAYS_SET_BIT \(.proc_id.always_set_bit)",
"#define SPEC_RUNTIME_DIR \"\(.paths.runtime_dir)\"",
"#define SPEC_FILE_MODE \(.paths.file_mode)",
"#define SPEC_NAME_FILE \"\(.paths.name_file)\"",
"#define SPEC_INSTANCE_FILE \"\(.paths.instance_file)\"",
"#define SPEC_INSTANCE_ID_HEX_DIGITS \(.paths.instance_id_hex_digits)",
"#define SPEC_SEGMENT_PATH \"\(.paths.segment)\"",
"#define SPEC_NOT_EMPTY_EVENT \"\(.paths.not_empty_event)\"",
"#define SPEC_NOT_FULL_EVENT \"\(.paths.not_full_event)\"",
"#define SPEC_EVENT_PATH \"\(.paths.event)\"",
"#define SPEC_LIFE_SOCKET \"\(.paths.life_socket)\"",
"#define SPEC_LIFE_SOCKET_HEX_DIGITS \(.paths.life_socket_procid_hex_digits)",
"#define SPEC_LIFE_SOCKET_TEMP_SUFFIX \"\(.paths.life_socket_temp_suffix)\"",
"#define SPEC_DEFAULT_CAPACITY \(.queue.default_capacity)u",
"#define SPEC_NOT_EMPTY_SUFFIX \"\(.queue.not_empty_suffix)\"",
"#define SPEC_NOT_FULL_SUFFIX \"\(.queue.not_full_suffix)\"",
"#define SPEC_SIGNAL_MAX_TOKENS \(.queue.signal_max_tokens)",
"#define SPEC_C2O_SUFFIX \"\(.channel.creator_to_opener_suffix)\"",
"#define SPEC_O2C_SUFFIX \"\(.channel.opener_to_creator_suffix)\"",
"#define SPEC_CONN_TYPE_DATA \(.conn.type_data)u",
"#define SPEC_CONN_TYPE_EOF \(.conn.type_eof)u",
"#define SPEC_SERVICE_REGISTRY_SUFFIX \"\(.service.registry_suffix)\"",
"#define SPEC_SERVICE_CLIENT_PREFIX \"\(.service.client_prefix)\"",
"#define SPEC_SERVICE_CLIENT_ID_HEX_DIGITS \(.service.client_id_hex_digits)",
"#define SPEC_SERVICE_RESERVED_TYPE_MIN UINT32_C(\(.service.reserved_type_min))",
"#define SPEC_SERVICE_TYPE_KNOCK UINT32_C(\(.service.type_knock))",
"#define SPEC_SERVICE_TYPE_HELLO UINT32_C(\(.service.type_hello))",
"#define SPEC_SERVICE_TYPE_ERROR UINT32_C(\(.service.type_error))",
"#define SPEC_SERVICE_SEQUENCE_SIZE \(.service.sequence_size)u",
"#define SPEC_SERVICE_FIRST_SEQUENCE \(.service.first_sequence)u"
