# Turns spec/wire.json into C macros for test_spec.c.
"/* Generated from spec/wire.json by tests/wire.jq. */",
"#define SPEC_RING_MAGIC UINT64_C(\(.ring.magic))",
"#define SPEC_RING_VERSION \(.ring.version)u",
"#define SPEC_HEADER_SIZE \(.ring.header_size)u",
"#define SPEC_CACHE_LINE \(.ring.cache_line)u",
"#define SPEC_MIN_CAPACITY \(.ring.min_capacity)u",
"#define SPEC_RECORD_HEADER_SIZE \(.ring.record_header_size)u",
"#define SPEC_RECORD_ALIGNMENT \(.ring.record_alignment)u",
"#define SPEC_TYPE_PADDING UINT32_C(\(.ring.type_padding))",
"#define SPEC_FIELD_COUNT \(.ring.fields | length)",
"#define SPEC_FIELDS \\",
(.ring.fields[] | "\t{\"\(.name)\", \(.offset), \(.size)}, \\"),
"",
"#define SPEC_DEFAULT_CAPACITY \(.queue.default_capacity)u",
"#define SPEC_SEGMENT_PATH \"\(.queue.segment_path)\"",
"#define SPEC_EVENT_PATH \"\(.queue.event_path)\"",
"#define SPEC_NOT_EMPTY_SUFFIX \"\(.queue.not_empty_suffix)\"",
"#define SPEC_NOT_FULL_SUFFIX \"\(.queue.not_full_suffix)\"",
"#define SPEC_SIGNAL_MAX_TOKENS \(.queue.signal_max_tokens)",
"#define SPEC_C2O_SUFFIX \"\(.channel.creator_to_opener_suffix)\"",
"#define SPEC_O2C_SUFFIX \"\(.channel.opener_to_creator_suffix)\"",
"#define SPEC_CONN_TYPE_DATA \(.conn.type_data)u",
"#define SPEC_CONN_TYPE_EOF \(.conn.type_eof)u"
