# Turns spec/wire.json into a C++ header for wire_test.cpp.
"// Generated from spec/wire.json by tests/wire.jq. Do not edit.",
"#pragma once",
"#include <cstddef>",
"#include <cstdint>",
"#include <string_view>",
"namespace spec {",
"inline constexpr std::uint64_t spec_version = \(.spec_version);",
"inline constexpr std::uint64_t ring_magic = \(.ring.magic)ULL;",
"inline constexpr std::uint64_t ring_version = \(.ring.version);",
"inline constexpr std::uint64_t header_size = \(.ring.header_size);",
"inline constexpr std::uint64_t cache_line = \(.ring.cache_line);",
"inline constexpr std::uint64_t min_capacity = \(.ring.min_capacity);",
"inline constexpr std::uint64_t record_header_size = \(.ring.record_header_size);",
"inline constexpr std::uint64_t record_alignment = \(.ring.record_alignment);",
"inline constexpr std::uint64_t type_padding = \(.ring.type_padding)ULL;",
"struct field { std::string_view name; std::uint64_t offset; std::uint64_t size; };",
"inline constexpr field ring_fields[] = {",
(.ring.fields[] | "\t{\"\(.name)\", \(.offset), \(.size)},"),
"};",
"inline constexpr std::uint64_t default_capacity = \(.queue.default_capacity);",
"inline constexpr std::string_view segment_path = \(.queue.segment_path | tojson);",
"inline constexpr std::string_view event_path = \(.queue.event_path | tojson);",
"inline constexpr std::string_view not_empty_suffix = \(.queue.not_empty_suffix | tojson);",
"inline constexpr std::string_view not_full_suffix = \(.queue.not_full_suffix | tojson);",
"inline constexpr std::uint64_t signal_max_tokens = \(.queue.signal_max_tokens);",
"inline constexpr std::string_view creator_to_opener_suffix = \(.channel.creator_to_opener_suffix | tojson);",
"inline constexpr std::string_view opener_to_creator_suffix = \(.channel.opener_to_creator_suffix | tojson);",
"inline constexpr std::uint64_t conn_type_data = \(.conn.type_data);",
"inline constexpr std::uint64_t conn_type_eof = \(.conn.type_eof);",
"}"
