# Turns spec/wire.json into a C++ header for wire_test.cpp.
"// Generated from spec/wire.json by tests/wire.jq. Do not edit.",
"#pragma once",
"#include <cstddef>",
"#include <cstdint>",
"#include <string_view>",
"namespace spec {",
"inline constexpr std::uint64_t spec_version = \(.spec_version);",
"inline constexpr std::uint64_t ring_magic = \(.ring.magic)ULL;",
"inline constexpr std::uint64_t ring_version = \(.ring.version);",
"inline constexpr std::uint64_t header_size = \(.ring.header_size);",
"inline constexpr std::uint64_t control_size = \(.ring.control_size);",
"inline constexpr std::uint64_t slots_offset = \(.ring.claim_slots.offset);",
"inline constexpr std::uint64_t slot_count = \(.ring.claim_slots.count);",
"inline constexpr std::uint64_t slot_size = \(.ring.claim_slots.slot_size);",
"inline constexpr std::uint64_t no_intent = \(.ring.claim_slots.no_intent)ULL;",
"inline constexpr std::uint64_t proc_none = \(.proc_id.none);",
"inline constexpr std::uint64_t proc_pending = \(.proc_id.pending);",
"inline constexpr std::uint64_t proc_watchable_bit = \(.proc_id.watchable_bit);",
"inline constexpr std::uint64_t proc_always_set_bit = \(.proc_id.always_set_bit);",
"inline constexpr std::uint64_t cache_line = \(.ring.cache_line);",
"inline constexpr std::uint64_t min_capacity = \(.ring.min_capacity);",
"inline constexpr std::uint64_t record_header_size = \(.ring.record_header_size);",
"inline constexpr std::uint64_t record_alignment = \(.ring.record_alignment);",
"inline constexpr std::uint64_t type_padding = \(.ring.type_padding)ULL;",
"struct field { std::string_view name; std::uint64_t offset; std::uint64_t size; };",
"inline constexpr field ring_fields[] = {",
(.ring.fields[] | "\t{\"\(.name)\", \(.offset), \(.size)},"),
"};",
"inline constexpr field slot_fields[] = {",
(.ring.claim_slots.fields[] | "\t{\"\(.name)\", \(.offset), \(.size)},"),
"};",
"inline constexpr std::uint64_t default_capacity = \(.queue.default_capacity);",
"inline constexpr std::string_view runtime_dir = \(.paths.runtime_dir | tojson);",
"inline constexpr std::string_view file_mode = \(.paths.file_mode | tojson);",
"inline constexpr std::string_view name_file = \(.paths.name_file | tojson);",
"inline constexpr std::string_view instance_file = \(.paths.instance_file | tojson);",
"inline constexpr std::uint64_t instance_id_hex_digits = \(.paths.instance_id_hex_digits);",
"inline constexpr std::string_view segment_path = \(.paths.segment | tojson);",
"inline constexpr std::string_view not_empty_event = \(.paths.not_empty_event | tojson);",
"inline constexpr std::string_view not_full_event = \(.paths.not_full_event | tojson);",
"inline constexpr std::string_view event_path = \(.paths.event | tojson);",
"inline constexpr std::string_view life_socket = \(.paths.life_socket | tojson);",
"inline constexpr std::uint64_t life_socket_procid_hex_digits = \(.paths.life_socket_procid_hex_digits);",
"inline constexpr std::string_view life_socket_temp_suffix = \(.paths.life_socket_temp_suffix | tojson);",
"inline constexpr std::string_view not_empty_suffix = \(.queue.not_empty_suffix | tojson);",
"inline constexpr std::string_view not_full_suffix = \(.queue.not_full_suffix | tojson);",
"inline constexpr std::uint64_t signal_max_tokens = \(.queue.signal_max_tokens);",
"inline constexpr std::string_view creator_to_opener_suffix = \(.channel.creator_to_opener_suffix | tojson);",
"inline constexpr std::string_view opener_to_creator_suffix = \(.channel.opener_to_creator_suffix | tojson);",
"inline constexpr std::uint64_t conn_type_data = \(.conn.type_data);",
"inline constexpr std::uint64_t conn_type_eof = \(.conn.type_eof);",
"inline constexpr std::string_view service_registry_suffix = \(.service.registry_suffix | tojson);",
"inline constexpr std::string_view service_client_prefix = \(.service.client_prefix | tojson);",
"inline constexpr std::uint64_t service_client_id_hex_digits = \(.service.client_id_hex_digits);",
"inline constexpr std::uint64_t service_reserved_type_min = \(.service.reserved_type_min);",
"inline constexpr std::uint64_t service_type_knock = \(.service.type_knock);",
"inline constexpr std::uint64_t service_type_hello = \(.service.type_hello);",
"inline constexpr std::uint64_t service_type_error = \(.service.type_error);",
"inline constexpr std::uint64_t service_sequence_size = \(.service.sequence_size);",
"inline constexpr std::uint64_t service_first_sequence = \(.service.first_sequence);",
"}"
